# Generated by Django 4.2.5 on 2023-09-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comp_task_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='none', max_length=100)),
                ('task_completed_time', models.DateTimeField(auto_now_add=True)),
                ('time_taken', models.CharField(default='none', max_length=100)),
            ],
            options={
                'db_table': 'comp_model',
            },
        ),
        migrations.CreateModel(
            name='non_comp_task_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='none', max_length=100)),
                ('task_created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'non_comp_model',
            },
        ),
    ]
