# Generated by Django 4.2.5 on 2023-09-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_comp_task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comp_task_model',
            name='time_taken',
        ),
    ]
